name: Build

on: [pull_request, push]

jobs:
  tests:
    name: Build-and-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AckeeCZ/load-xcode-version@1.0
      - uses: actions/cache@v2
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      - uses: actions/cache@v2
        id: pods-cache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      - name: Install Carthage dependencies if not in cache
        if: steps.carthage-cache.outputs.cache-hit != 'true'
        run: |
          carthage bootstrap --platform iOS --cache-builds --use-xcframeworks
      - name: Install CocoaPods dependencies if not in cache
        if: steps.pods-cache.outputs.cache-hit != 'true'
        run: |
          pod install
      - name: Install gems
        run: bundle install
      - name: Select XCode
        run: sudo xcode-select -switch '/Applications/Xcode_12.4.app'
      - name: XCode version
        run: /usr/bin/xcodebuild -version
      - name: Run clean build
        run: xcodebuild clean build -scheme Development -workspace 'MastersThesisIOS.xcworkspace' -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
      - name: Run unit tests
        run: xcodebuild test -scheme Development -workspace 'MastersThesisIOS.xcworkspace' -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
